### ISSUE TITLE
Feature Request: An option for selecting the section in the config to open.

### ISSUE THREAD

**Issue by DMBuce** [davatorium/rofi-blezz#1]
Blezz has a `-d` option to choose which dir in the config to open. As far as I can tell this is not possible with rofi-blezz, which always starts by displaying the first dir defined in the config.

Currently I am using a [wrapper script](https://github.com/DMBuce/i3b/blob/master/bin/rofi-blezz) for this functionality, but it would be nice if rofi-blezz had the feature baked in.

An example of how this would be useful: I have a config similar to the one below and use my wrapper script to bind Super+z to the "Main" dir, Super+m to the "Music" dir, and Super+p to the "Password" dir. Without the wrapper script I would have to have different copies of nearly identical config files, just with the order of the dirs changed. Which is not ideal.

    Main:
    dir(m,Music)
    dir(p,Password)
    
    Music:
    act(m,Mpd,     music mps play )
    act(p,Pandora, music pandora play )
    act(r,Radio,   music radio play )
    act(c,Choose,  music choose )
    
    Password:
    act(p,Password, rofi-pass copyPass)
    act(c,Copy,     rofi-pass copyMenu)
    act(l,Launch,   rofi-pass openUrl)
    act(n,New,      rofi-pass --insert)
    act(o,Other,    rofi-pass actionMenu)

**Comment by DaveDavenport** [comment]
```c
    find_arg_str( "-blezz-config", &dpath);
```

I think -blezz-config should work.

**Comment by DaveDavenport** [comment]
owh fun :D , lets see

**Comment by DaveDavenport** [comment]
That works fine for me

**Comment by DaveDavenport** [comment]
hopefully fixed.. (its been way to long since I done anything on this plugin)

**Comment by DMBuce** [comment]
Works great, thanks a bunch!
